/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingInfo: typeof import('./src/components/BuildingInfo.vue')['default']
    BuildingPanel: typeof import('./src/components/BuildingPanel.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    SceneCanvas: typeof import('./src/components/SceneCanvas.vue')['default']
    StatsPanel: typeof import('./src/components/StatsPanel.vue')['default']
  }
}
